name: Build Microserviço Grupo04

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Início do build
        run: echo "Iniciando o processo de build..."

      - name: Fim do build
        run: echo "Build finalizado com sucesso."
#fim