AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Template para criar uma instância EC2 Ubuntu com Apache instalado."

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      KeyName: "fatec-5sem"
      ImageId: "ami-0fc5d935ebf8bc3bc" # AMI Ubuntu mais recente na região (verifique a ID correta para sua região)
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: "subnet-088043a30f2198697"
          GroupSet:
            - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo apt update -y
          sudo apt install apache2 -y
          sudo systemctl start apache2
          sudo systemctl enable apache2
          sudo ufw disable
      Tags:
        - Key: "Name"
          Value: "Ubuntu-WebServer"

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Habilita acesso HTTP, HTTPS e SSH"
      VpcId: "vpc-00db397b"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"

Outputs:
  InstancePublicIP:
    Description: "Public IP address of the EC2 instance"
    Value: !GetAtt EC2Instance.PublicIp