name: Testar Dockerfile do Auth

on: [push, pull_request]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build da imagem Docker
        run: docker build -t auth-service ./auth
