name: Teste Pipeline
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do código
              uses: actions/checkout@v3
            - name: Executar comando
              run: echo "Pipeline funcionando!"