name: Node.js CI

on:
  push:
    branches:
      - grupo/servico-de-notificacoes
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run service briefly to check start
        run: node index.js &
