name: Testar Microsserviço Auth (Next.js)

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
    - name: Fazer Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' 
        cache: 'npm' 
        cache-dependency-path: '**/package-lock.json' 

    - name: Instalar dependências
      run: npm ci 

    - name: Executar testes (Next.js)
      run: npm test

    - name: Exibir mensagem de sucesso nos testes
      run: echo "--- Testes do Microsserviço Auth (Next.js) concluídos com sucesso ---"
      if: success() 

    - name: Exibir mensagem de falha nos testes
      run: echo "--- Testes do Microsserviço Auth (Next.js) falharam ---"
      if: failure()