name: Testes Microserviço Grupo04

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          cd microservicos-grupo04
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes com Pytest
        run: |
          cd microservicos-grupo04
          pytest -v
#fim