name: Validate CloudFormation Template - Grupo 02
on:
  pull_request:
    paths:
      - 'iac/grupo02.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cfn-lint and yamllint
        run: |
          pip install cfn-lint yamllint

      - name: Run CFN Linter
        run: |
          cfn-lint iac/grupo02.yaml > cfn_lint_report.txt || true

      - name: Run YAML Lint
        run: |
          yamllint iac/grupo02.yaml > yaml_lint_report.txt || true

      - name: Generate Validation Report
        run: |
          echo "# CloudFormation Template Validation Report" > validation_report.md
          echo "## CFN-Lint Results" >> validation_report.md
          cat cfn_lint_report.txt >> validation_report.md
          echo "## YAML-Lint Results" >> validation_report.md
          cat yaml_lint_report.txt >> validation_report.md

      - name: Upload Validation Report
        uses: actions/upload-artifact@v3
        with:
          name: validation-report
          path: validation_report.md

      - name: Check for Errors
        run: |
          if grep -q "E[0-9]" cfn_lint_report.txt; then
            echo "CloudFormation template validation failed!"
            exit 1
          fi