name: Validate CloudFormation Template
on:
  push:
  pull_request:
    
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          pip install cfn-lint yamllint

      - name: Fix YAML formatting issues
        run: |
          # Converte finais de linha para o formato Unix (LF)
          dos2unix iac/Grupo1.yaml
          
          # Remove espaços em branco no final das linhas
          sed -i 's/[[:space:]]*$//' iac/Grupo1.yaml
          
          # Garante que haja uma nova linha no final do arquivo
          echo "" >> iac/Grupo1.yaml

      - name: Validate CloudFormation templates with cfn-lint
        run: |
          echo "Validating with cfn-lint..."
          cfn-lint iac/Grupo1.yaml

      - name: Validate YAML syntax with yamllint
        run: |
          echo "Validating YAML syntax..."
          yamllint iac/Grupo1.yaml

      - name: Generate validation report
        if: always()
        run: echo "Validation completed!"